groff, dbus, ncmpcpp, audio, other tools

diff --git a/.config/aliasrc b/.config/aliasrc
--- a/.config/aliasrc
+++ b/.config/aliasrc
@@ -5,6 +5,7 @@ alias mpv="mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)"
 alias calcurse="calcurse -D ~/.config/calcurse"
 alias f="$FILE"
 alias g="git"
+alias pgl="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"
 alias e="$EDITOR"
 alias x="sxiv -ft *"
 alias ls="ls -hA --color=auto --group-directories-first"
@@ -21,6 +22,8 @@ alias dot='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
 alias ghci-core="ghci -ddump-simpl -dsuppress-idinfo -dsuppress-coercions -dsuppress-type-applications -dsuppress-uniques -dsuppress-module-prefixes"
 alias gh="gen-hie | tee hie.yaml"
 alias web="w3m duckduckgo.com/lite"
+alias cp="advcp -g"
+alias mv="advmv -g"
 
 command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.
 
@@ -51,3 +54,11 @@ IFS=$'\n' read -r -d '' -a __aliases <<< "$(alias -p | sed 's/=.*//g' | sed 's/a
 for i in "${__aliases[@]}"; do
 	complete -F _complete_alias "$i"
 done
+
+npup() {
+	[ -r "$1" ] || {
+		echo "Can't access $1"
+		return 1
+	}
+	curl -F"file=@$1" https://0x0.st
+}
